version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "createSetting"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fn49rix9hvm8"
s3_prefix = "createSetting"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
confirm_changeset = true
